### ISSUE TITLE
node issue 

### ISSUE THREAD

**Issue by SkullCandby** [bilix-software/solana-pump-fun#4]
I tested this code with my decent QuickNode rpc endpoint (the one for) and it did not work (block height exceeded.), but it works with public main node. Any advices on what node I should get?

**Comment by bilix-software** [comment]
Hi, as far as I know there are a few things you can do for tx inclusion and those are as follows:
- Up priority fee (increases chance of inclusion if the tx reaches the validator)
- Send identical tx multiple times (increases change of tx reaching validator)
- Bundle tx instead through jito
- Get your own node/ paid tier of quicknode or helius

But I'm not an expert on transaction inclusion so there will be others more qualified to answer this

**Comment by SkullCandby** [comment]
I have my own node bought from QuickNode. Also, I was using pumpportal api before with node and when I was sendim txs in the loop moneys were always debited for JITO in every failed transaction

**Comment by bilix-software** [comment]
If you bundle it yourself with a jito tip in the transaction, you will not pay the tip unless it executes.

**Comment by SkullCandby** [comment]
PS C:\Users\gdmes\solana-pump-fun> node example.js
Error sending transaction: TransactionExpiredBlockheightExceededError: Signature 44o76QmDC65dsUKY3aPNxGEGKeQ37WE5bPk4FuwG2nFY164wEVfwYhQKPAy78G8dXCqYy5nYmPCJJfvgwms27c4n has expired: block height exceeded.
    at Connection.confirmTransactionUsingBlockHeightExceedanceStrategy (C:\Users\gdmes\solana-pump-fun\node_modules\@solana\web3.js\lib\index.cjs.js:6565:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Connection.confirmTransaction (C:\Users\gdmes\solana-pump-fun\node_modules\@solana\web3.js\lib\index.cjs.js:6393:14)
    at async sendAndConfirmTransaction (C:\Users\gdmes\solana-pump-fun\node_modules\@solana\web3.js\lib\index.cjs.js:2181:15) {
  signature: '44o76QmDC65dsUKY3aPNxGEGKeQ37WE5bPk4FuwG2nFY164wEVfwYhQKPAy78G8dXCqYy5nYmPCJJfvgwms27c4n'
}
Buy transaction confirmed: null
Error sending transaction: TransactionExpiredBlockheightExceededError: Signature 4H1F9iABSE1XcipAbmYJkme26bv2syG3VJdEGSceXNtysupkZkVAHQj5Qb9Mjbz7ktX6d2LnPdf2yjNXL44HqzV9 has expired: block height exceeded.
    at Connection.confirmTransactionUsingBlockHeightExceedanceStrategy (C:\Users\gdmes\solana-pump-fun\node_modules\@solana\web3.js\lib\index.cjs.js:6565:15)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Connection.confirmTransaction (C:\Users\gdmes\solana-pump-fun\node_modules\@solana\web3.js\lib\index.cjs.js:6393:14)
    at async sendAndConfirmTransaction (C:\Users\gdmes\solana-pump-fun\node_modules\@solana\web3.js\lib\index.cjs.js:2181:15) {
  signature: '4H1F9iABSE1XcipAbmYJkme26bv2syG3VJdEGSceXNtysupkZkVAHQj5Qb9Mjbz7ktX6d2LnPdf2yjNXL44HqzV9'
}
Buy transaction confirmed: null
Transaction confirmed with signature: 2NfUsLpyusYn7xArxaXojbWNXUTrz6cVQL7dgXmh5S26mURpYWj4yURjDbqV5GFDQHWHjpqDWbBZYeCnKsDpkv57
Buy transaction confirmed: 2NfUsLpyusYn7xArxaXojbWNXUTrz6cVQL7dgXmh5S26mURpYWj4yURjDbqV5GFDQHWHjpqDWbBZYeCnKsDpkv57
PS C:\Users\gdmes\solana-pump-fun> node example.js
Error sending transaction: TransactionExpiredBlockheightExceededError: Signature 3UKS6U649cphG6KF7e4BiGB2P82w4eZh4rCTr8t9tviA9v8AuA3wZXmwzG3ZHbVhdV15tmG5WtUN5aGPXdM5UYHS has expired: block height exceeded.
    at Connection.confirmTransactionUsingBlockHeightExceedanceStrategy (C:\Users\gdmes\solana-pump-fun\node_modules\@solana\web3.js\lib\index.cjs.js:6565:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Connection.confirmTransaction (C:\Users\gdmes\solana-pump-fun\node_modules\@solana\web3.js\lib\index.cjs.js:6393:14)
    at async sendAndConfirmTransaction (C:\Users\gdmes\solana-pump-fun\node_modules\@solana\web3.js\lib\index.cjs.js:2181:15) {
  signature: '3UKS6U649cphG6KF7e4BiGB2P82w4eZh4rCTr8t9tviA9v8AuA3wZXmwzG3ZHbVhdV15tmG5WtUN5aGPXdM5UYHS'
}
Buy transaction confirmed: null
Transaction confirmed with signature: 1on5njiUX3FYhdEeBd6wE8GRAu3bxUDhB2tpN4cPVE7HBxV6nyjkY9hwwDoWfkGtx5eCKqhxEtGkvCPpc3Vk43m
Buy transaction confirmed: 1on5njiUX3FYhdEeBd6wE8GRAu3bxUDhB2tpN4cPVE7HBxV6nyjkY9hwwDoWfkGtx5eCKqhxEtGkvCPpc3Vk43m

but it takes like 3 minutes to buy a token

**Comment by bilix-software** [comment]
What are you using as priority fee? Have you tried upping that?

**Comment by SkullCandby** [comment]
0.01, but does it affect transaction speed if I am the only one who is buying a token

**Comment by bilix-software** [comment]
Well it does affect inclusion rate, for the validator it doesnt matter what your transaction is doing. But 0.01 is already very high so i would not increase that further. Have you recompiled the typescript (npx tsc), after making changes in the example.ts file?

**Comment by SkullCandby** [comment]
no I just recompiled it using npx tsc
